haspiagge(bari).
haspiagge(napoli).
haspiagge(palermo).

%regola che ci permette di sapere se x è una città di mare
hamare(X) :- haspiagge(X).


spiaggia(pane_e_pomodoro,bari).
spiaggia(baia_rocce_verdi,napoli).
spiaggia(bagno_elena,napoli).
spiaggia(spiaggia_costa_sud,palermo).
spiaggia(spiaggia_sperone,palermo).

posto(museo_francesco_messina,milano).
posto(pinacoteca_di_brera,milano).
posto(museo_del_900,milano).
posto(forma_gallery,milano).
posto(museo_del_cenacolo_vinciano,milano).
posto(museo_teatrale_alla_scala,milano).
posto(museo_mangimi_bonomi,milano).
posto(musei_del_castello,milano).
posto(museo_diocesano_di_milano,milano).
posto(museo_di_santeustorgio,milano).
posto(museo_astronomico_di_brera,milano).
posto(gallerie_ditalia,milano).
posto(museo_poldi_pezzoli,milano).
posto(museo_interattivo_del_cinema,milano).
posto(museo_egizio,milano).
posto(casa_museo_boschi_di_stefano,milano).
posto(civica_raccolta_delle_stampe_achille_bertarelli,milano).
posto(museo_bagatti_valsecchi,milano).
posto(museo_degli_strumenti_musicali,milano).
posto(museo_dei_mobili_e_delle_sculture_lignee,milano).
posto(pinacoteca_ambrosiana,milano).
posto(museo_darte_antica,milano).
posto(pinacoteca_del_castello_sforzesco,milano).
posto(sacrestia_del_bramante,milano).
posto(museo_macchina_da_scrivere,milano).
posto(fondazione_prada,milano).
posto(museo_pieta_rondanini,milano).
posto(museo_delle_culture,milano).
posto(albero_della_vita,milano).
posto(cappella_portinari,milano).
posto(cripta_di_san_giovanni_in_conca,milano).
posto(f_84_f_thunderstreak,milano).
posto(fiat_g91r,milano).
posto(north_american_fiat_f86_k,milano).
posto(the_hub,milano).
posto(museo_nazionale_della_montagna_duca_degli_abru,torino).
posto(museo_egizio,torino).
posto(galleria_sabauda,torino).
posto(museo_del_risorgimento,torino).
posto(armeria_reale,torino).
posto(pietro_micca_museum,torino).
posto(museo_del_carcere_le_nuove,torino).
posto(centro_storico_fiat,torino).
posto(museo_regionale_di_scienze_naturali,torino).
posto(mao_museo_di_arte_orientale,torino).
posto(museo_nazionale_del_cinema,torino).
posto(museo_della_radio_e_della_televisione,torino).
posto(museo_civico_darte_antica,torino).
posto(museo_dellistituto_di_anatomia,torino).
posto(mau___museo_darte_urbana,torino).
posto(museo_scolastico_della_scuola_primaria_ludovico,torino).
posto(castello_del_borgo_medioevale,torino).
posto(castello_del_valentino,torino).
posto(cavallerizza_reale,torino).
posto(chiostro_chiesa_ss_martiri,torino).
posto(portone_del_diavolo,torino).
posto(casa_di_augusto,roma).
posto(museo_della_civilta_romana,roma).
posto(museo_dellastronomia_e_planetario,roma).
posto(museo_storico_dei_bersaglieri,roma).
posto(galleria_spada,roma).
posto(museo_di_roma,roma).
posto(museo_centrale_del_risorgimento,roma).
posto(museo_nazionale_romano,roma).
posto(palazzo_doria_pamphilj,roma).
posto(museo_pietro_canonica,roma).
posto(museo_nazionale_etrusco_di_villa_giulia,roma).
posto(sacrario_delle_bandiere_delle_forze_armate,roma).
posto(museo_nazionale_romano___crypta_balbi,roma).
posto(galleria_borghese,roma).
posto(museo_ebraico_di_roma,roma).
posto(museo_storico_dellarma_dei_carabinieri,roma).
posto(galleria_colonna,roma).
posto(chiostro_del_bramante,roma).
posto(museo_della_mente,roma).
posto(explora,roma).
posto(museo_napoleonico_di_roma,roma).
posto(museo_nazionale_delle_paste_alimentari,roma).
posto(galleria_nazionale_darte_antica,roma).
posto(museo_barracco,roma).
posto(case_romane_del_celio,roma).
posto(casa_di_goethe,roma).
posto(museo_palatino,roma).
posto(museo_storico_della_liberazione,roma).
posto(museo_delle_poste_e_telecomunicazioni,roma).
posto(vigamus_museo_del_videogioco,roma).
posto(macro_testaccio,roma).
posto(museo_hendrik_christian_andersen,roma).
posto(museo_boncompagni_ludovisi_per_le_arti_decorativ,roma).
posto(museo_etnografico_luigi_pigorini,roma).
posto(museo_nazionale_dellalto_medioevo,roma).
posto(museo_nazionale_darte_orientale_gtucci,roma).
posto(mueso_delle_forze_alleate_roma,roma).
posto(giacomo_guidi_arte_contemporanea,roma).
posto(addax,roma).
posto(african_wild_dog,roma).
posto(antelope,roma).
posto(aquatic_birds,roma).
posto(asian_lion,roma).
posto(banteng,roma).
posto(bocca_della_verita,roma).
posto(brown_bear,roma).
posto(bunker_ferro_di_cavallo,roma).
posto(camel,roma).
posto(cannone_di_mezzogiorno,roma).
posto(catacombe_di_san_sebastiano,roma).
posto(elephant,roma).
posto(european_bison,roma).
posto(felline,roma).
posto(fonte_dellacqua_sacra,roma).
posto(giraffe,roma).
posto(golden_eagle,roma).
posto(grey_seal,roma).
posto(himalayan_thar,roma).
posto(istituto_italiano_di_numismatica,roma).
posto(japanese_macaque,roma).
posto(mandrill,roma).
posto(mangabey,roma).
posto(monumento_al_finanziere,roma).
posto(mouflon,roma).
posto(nile_lechwe,roma).
posto(ninfeo_di_egeria,roma).
posto(onager,roma).
posto(ostrich,roma).
posto(pantheon,roma).
posto(piazza_mincio___quartiere_coppede,roma).
posto(platani_orientali_del_seicento,roma).
posto(primo_miracolo,roma).
posto(raptors,roma).
posto(reliquia_di_san_giovanni_battista,roma).
posto(rovine_mausoleo_santa_costanza,roma).
posto(san_pietro_dal_buco_della_serratura,roma).
posto(scimpanze_chimps,roma).
posto(sika_deer,roma).
posto(tapir,roma).
posto(templum_martis_ultoris,roma).
posto(tiger,roma).
posto(torre_di_perna,roma).
posto(vittoriano,roma).
posto(wallaby,roma).
posto(zebra,roma).
posto(museo_dellosservatorio_astronomico,napoli).
posto(corporea,napoli).
posto(museo_hermann_nitsch,napoli).
posto(museo_ferroviario_nazionale_di_pietrarsa,napoli).
posto(arca,napoli).
posto(musa___sezione_di_anatomia,napoli).
posto(musa___sezione_di_farmacologia,napoli).
posto(museo_nazionale_di_capodimonte,napoli).
posto(gallerie_ditalia,napoli).
posto(circolo_artistico_politecnico,napoli).
posto(museo_giuseppe_caravita_principe_di_sirignano,napoli).
posto(museo_civico_gaetano_filangieri,napoli).
posto(palazzo_delle_arti_napoli,napoli).
posto(museo_nazionale_della_ceramica_duca_di_martina,napoli).
posto(napoli_sotterranea,napoli).
posto(odeon,napoli).
posto(teatro,napoli).
posto(museo_di_scienze_della_terra_di_bari,bari).
posto(museo_di_zoologia,bari).
posto(museo_collezione_di_fisica,bari).
posto(museo_diocesano_di_san_nicola,bari).
posto(orto_botanico,bari).
posto(museo_strumenti_di_chimica,bari).
posto(erbario_di_villa_la_rocca,bari).
posto(soprintendenza_archeologica_della_puglia___nucle,bari).
posto(cittadella_mediterranea_della_scienza,bari).
posto(porto_romano,bari).
posto(museo_dellislam,palermo).
posto(galleria_regionale,palermo).
posto(museo_di_geologia_gemmelaro,palermo).
posto(museo_internazionale_delle_marionette_antonio_pa,palermo).
posto(museo_darte_e_archeologia_ignazio_mormino,palermo).
posto(museo_del_mare,palermo).
posto(museo_storico_dei_motori_e_dei_meccanismi,palermo).
posto(museo_dellosservatorio_astronomico,palermo).
posto(museo_del_risorgimento_vittorio_emanuele_orlando,palermo).
posto(museo_di_mineralogia,palermo).
posto(museo_di_palazzo_mirto,palermo).
posto(galleria_darte_moderna,palermo).
posto(palazzo_dei_normanni___cappella_palatina,palermo).
posto(museo_darte_contemporanea_della_sicilia,palermo).
posto(museo_etnografico_siciliano_giuseppe_pitra,palermo).
posto(pietro_doderlein,palermo).
posto(esposizione_strumenti_medici_ex_ospedale_psichia,palermo).
posto(albergo_delle_povere,palermo).

sport(stadio_giuseppe_meazza,milano).
sport(stadio_olimpico,roma).
sport(stadio_diego_armando_maradona,napoli).
sport(stadio_renzo_barbera,palermo).
sport(stadio_san_nicola,bari).
sport(allianz_stadium,torino).

parcodivertimenti(gardaland,milano).
parcodivertimenti(leolandia,milano).
parcodivertimenti(acquatica_park,milano).
parcodivertimenti(acquaworld_,milano).
parcodivertimenti(acquapark_lodi,milano).
parcodivertimenti(le_cornelle,milano).
parcodivertimenti(ondaland_,torino).
parcodivertimenti(acquajoy,torino).
parcodivertimenti(magicland,roma).
parcodivertimenti(zoomarine,roma).
parcodivertimenti(cinecittaworld,roma).
parcodivertimenti(acquafelix,roma).
parcodivertimenti(bioparco,roma).
parcodivertimenti(hydromania,roma).
parcodivertimenti(valle_dellorso,napoli).
parcodivertimenti(aquarium,napoli).
parcodivertimenti(liberty_city_fun,napoli).
parcodivertimenti(acquapark_free_time,napoli).
parcodivertimenti(ditellandia_air_acqua_park,napoli).
parcodivertimenti(aquapark_le_campole,napoli).
parcodivertimenti(indiana_park,napoli).
parcodivertimenti(parco_montevergine,napoli).
parcodivertimenti(zoo_di_napoli,napoli).
parcodivertimenti(fasanolandia,bari).
parcodivertimenti(zoo_safari,bari).
parcodivertimenti(indiana_park_,bari).
parcodivertimenti(acquapark_monreale,palermo).
parcodivertimenti(parco_avventura_madonie,palermo).


cucina(pasta_con_le_sarde,palermo).
cucina(arancina,palermo).
cucina(stigghiole,palermo).
cucina(cannolo_siciliano,palermo).
cucina(pizza_al_piatto_napoletana,napoli).
cucina(cuoppo,napoli).
cucina(sfogliatella_frolla,napoli).
cucina(sfogliatella_riccia,napoli).
cucina(pizza_a_portafoglio,napoli).
cucina(pasta_patate_e_provola,napoli).
cucina(baba,napoli).
cucina(pizza_fritta,napoli).
cucina(pasta_allamatriciana,roma).
cucina(pasta_alla_carbonara,roma).
cucina(pasta_cacio_e_pepe,roma).
cucina(coda_alla_vaccinara,roma).
cucina(saltimbocca_alla_romana,roma).
cucina(carciofi_alla_giudia,roma).
cucina(vitello_tonnato,torino).
cucina(brasato_al_barolo,torino).
cucina(agnolotti,torino).
cucina(bagna_cauda,torino).
cucina(cotoletta_alla_milanese,milano).
cucina(risotto_alla_milanese,milano).
cucina(focaccia_barese,bari).
cucina(tiella_barese,bari).
cucina(panzerotti,bari).
cucina(sgagliozze,bari).
cucina(orecchiette_con_cime_di_rapa,bari).
cucina(spaghetti_allassassina,bari).
cucina(zampina,bari).
cucina(tetta_della_monaca,bari).
cucina(polpo_arrostito,bari).
cucina(cartellate_pugliesi,bari).